# Full playbook re-run, Oct 8 2026
LIB="ridgefield-library"; WF="weir-farm-nhp"; WC="woodcock-nature-center"; REC="ridgefield-parks-recreation-ridgefield-r-2"
LH="lounsbury-house"; RP="richardson-park"; JL="jesse-lee-church"; FES="farmingville-school"; PPS="peter-parley"; BGC="bgc-ridgefield"
TOWN["venues"].update({LH:["Lounsbury House","316 Main St"],RP:["Richardson Park","729 N Salem Rd"],JL:["Jesse Lee Church","207 Main St"],FES:["Farmingville Elementary School","324 Farmingville Rd"],PPS:["Peter Parley Schoolhouse","West Ln at South Salem Rd"],BGC:["Boys & Girls Club of Ridgefield","41 Governor St"]})
TOWN["venueMeta"].update({LH:[None,1],RP:[None,0],JL:[None,0],FES:[None,0],PPS:[None,1],BGC:[None,0]})
for e in TOWN["events"]:
    if e["t"]=="Story Time for Kids": e["when"].insert(1,W("2026-10-17",[["10:30","11:30"]]))
    if e["t"]=="All Ages Discovery Tour": e.pop("s",None); e["when"]=D(["2026-11-21","2026-12-19"],[["13:00","14:00"]])
TOWN["tba"]=[x for x in TOWN["tba"] if x["t"] not in ("Trunk-or-Treat with the Ridgefield Police","Jesse Lee Pumpkin Patch")]
WCS="https://www.woodcocknaturecenter.org/upcomingevents"; WFS="https://www.nps.gov/wefa/planyourvisit/featured-programs.htm"; LHS="https://lounsburyhouse.org/calendar/"
TOWN["events"]+=[
 {"t":"Jesse Lee Pumpkin Patch","v":JL,"special":"fall","s":[[1,[["14:00","18:00"]],"2026-10-08","2026-10-31"],[2,[["14:00","18:00"]],"2026-10-08","2026-10-31"],[3,[["14:00","18:00"]],"2026-10-08","2026-10-31"],[4,[["14:00","18:00"]],"2026-10-08","2026-10-31"],[5,[["14:00","18:00"]],"2026-10-08","2026-10-31"],[6,[["10:00","18:00"]],"2026-10-08","2026-10-31"],[0,[["10:00","18:00"]],"2026-10-08","2026-10-31"]],"ages":"All ages","a":B+["big"],"free":True,"price":"Free to visit; pumpkins priced individually","drop":True,"src":"https://jesseleechurch.com/pumpkin-patch/",
  "blurb":"The church lawn fills with pumpkins on Main Street; pick one out and take photos. Open weekdays 2–6 and weekends 10–6."},
 {"t":"Art and Agriculture Tour","v":WF,"when":[W("2026-10-11",[["10:00","11:00"]])],"ages":"All ages","a":["big"],"free":True,"price":"Free","drop":True,"src":WFS,
  "blurb":"A ranger tour of the farm's barns, farming history and artwork; meet at the Visitor Center sign."},
 {"t":"Hocus Pocus Family Screening","v":LIB,"special":"hw","when":[W("2026-10-12",[["14:00","15:40"]])],"ages":"Grades K–5 + family","a":["big"],"free":True,"price":"Free","drop":True,"src":"https://inridgefield.com/events/hocus-pocus-family-screening/",
  "blurb":"A school-holiday showing of Hocus Pocus; an adult must stay."},
 {"t":"Paranormal Park Ghost Walk","v":RP,"special":"hw","when":D(["2026-10-16","2026-10-17","2026-10-23","2026-10-24"],[["18:30","21:00"]]),"ages":"Ages 10+ (under 14 with an adult)","a":["big"],"free":False,"price":"Tickets online","rsvp":True,"check":True,"src":"https://inridgefield.com/events/paranormal-park-ghost-walk/",
  "blurb":"A 15–20 minute haunted trail walk after dark with live actors, run by the Ridgefield Fathers Club. Scary; best for older kids."},
 {"t":"Nature Center Open House","v":WC,"when":D(["2026-10-17","2026-11-08"],[["10:00","12:00"]]),"ages":"All ages","a":B+["big"],"free":True,"price":"Free","drop":True,"src":WCS,
  "blurb":"Drop in to meet Woodcock's animal ambassadors."},
 {"t":"Fall Hike Weekend at Weir Farm","v":WF,"special":"fall","when":D(["2026-10-17","2026-10-18"],[["09:30","11:00"]]),"ages":"Families","a":["preschool","big"],"free":True,"price":"Free","drop":True,"src":WFS,
  "blurb":"A ranger hike about trees and why leaves change color, then a leaf-print or landscape craft."},
 {"t":"Critters and Costumes!","v":WC,"special":"hw","when":[W("2026-10-23",[["10:30","12:00"]])],"ages":"Ages 2–6 + caregiver","a":["toddler","preschool"],"free":False,"price":"$30 per child","rsvp":True,"src":WCS,
  "blurb":"Hike in costume following animal clues, meet a tarantula and an albino snake, then hear a story. Bring a snack."},
 {"t":"Autumn Leaves and Amphibians Hike","v":WC,"when":[W("2026-10-24",[["10:00","11:30"]])],"ages":"Families","a":["big"],"free":True,"price":"Free","rsvp":True,"src":WCS,
  "blurb":"Search the leaf litter for salamanders on a guided family hike."},
 {"t":"Zombie Tag & Food Drive","v":FES,"special":"hw","when":[W("2026-10-24",[["15:30","17:00"]])],"ages":"Kids","a":["big"],"free":True,"price":"Free (bring a food donation)","drop":True,"check":True,"src":"https://inridgefield.com/events/zombie-tag-food-drive/",
  "blurb":"A big game of zombie tag hosted by Cub Scout Pack 116; bring a nonperishable food item."},
 {"t":"Halloween at the Schoolhouse","v":PPS,"special":"hw","when":[W("2026-10-25",[["13:00","16:00"]])],"ages":"All ages","a":["preschool","big"],"free":True,"price":"Free","drop":True,"src":"https://ridgefieldhistoricalsociety.org/event/24119/",
  "blurb":"Come in costume to the one-room schoolhouse for treats and spooky local-history stories."},
 {"t":"Halloween Storytime & Parade","v":LIB,"special":"hw","when":[W("2026-10-31",[["10:30","11:00"]])],"ages":"Young kids","a":["toddler","preschool"],"free":True,"price":"Free","rsvp":True,"src":"https://inridgefield.com/events/halloween-storytime-and-parade/",
  "blurb":"Halloween stories, then a costume parade around the library with goodie bags. Registration encouraged."},
 {"t":"Trunk-or-Treat with the Ridgefield Police","v":LH,"special":"hw","when":[W("2026-10-31",[["17:00","20:30"]])],"ages":"All ages","a":B+["big"],"free":True,"price":"Free","drop":True,"src":LHS,
  "blurb":"Decorated trunks and treats outdoors at Lounsbury House on Halloween night."},
 {"t":"Storytime: On the Trails","v":WC,"when":[W("2026-11-02",[["10:00","11:00"]])],"ages":"Ages 2–6 + caregiver","a":["toddler","preschool"],"free":True,"price":"Free","rsvp":True,"src":WCS,
  "blurb":"A short trail walk about fall nature, then a story."},
 {"t":"Free Family Fun Day","v":REC,"when":[W("2026-11-03",[["12:00","16:00"]])],"ages":"All ages","a":B+["big"],"free":True,"price":"Free","drop":True,"src":"https://www.ridgefieldparksandrec.org/programs/events/30486",
  "blurb":"An Election Day open house: inflatables, Big Blue Blocks, recreation swim 2–4 and a pool slide (42-inch minimum) 2:30–3:30."},
 {"t":"Surviving Winter as a Turtle Hike","v":WC,"when":[W("2026-11-07",[["13:00","14:30"]])],"ages":"Families","a":["big"],"free":True,"price":"Free","rsvp":True,"src":WCS,
  "blurb":"A guided hike about how turtles and other animals get through a Connecticut winter."},
 {"t":"Veterans Day Ceremony","v":LH,"when":[W("2026-11-11",[["11:00","12:00"]])],"ages":"All ages","a":["big"],"free":True,"price":"Free","drop":True,"src":LHS,
  "blurb":"The town's ceremony with American Legion Post 78, with refreshments after."},
 {"t":"Kids Night Out: Glow Night","v":REC,"when":[W("2026-11-20",[["17:00","19:30"]])],"ages":"Grades K–4","a":["big"],"free":False,"price":"$35 members, $40 non-members","rsvp":True,"src":"https://www.ridgefieldparksandrec.org/youth-programs/events/30551",
  "blurb":"Karaoke, dancing, crafts, pizza and popsicles; wear white or neon."},
 {"t":"Turkey Pardon","v":LH,"when":[W("2026-11-22",[["12:00","13:00"]])],"ages":"All ages","a":B+["big"],"free":True,"price":"Free","drop":True,"src":LHS,
  "blurb":"The First Selectman pardons 'Mr. Gobble'; meet the turkey and play lawn games. Rain or shine."},
 {"t":"Turkey Trot Kids' Fun Run","v":BGC,"when":[W("2026-11-26",[["08:00","08:20"]])],"ages":"Kids","a":["preschool","big"],"free":False,"price":"$22.95 (5K $38.96)","rsvp":True,"src":"https://www.givesignup.org/Race/CT/Ridgefield/RidgefieldTurkeyTrot",
  "blurb":"The Boys & Girls Club's 45th Thanksgiving trot: a short kids' run at 8, then the 5K at 8:30. Prices go up after Oct 31."},
 {"t":"Holiday Stroll North Pole","v":LH,"special":"hol","when":[W("2026-12-04",[["18:00","21:00"]])],"ages":"All ages","a":B+["big"],"free":True,"price":"Free","drop":True,"check":True,"src":LHS,
  "blurb":"During the Holiday Stroll: Santa and Mrs. Claus, live reindeer, selfies with elves and postcards for the troops."},
]
TOWN["tba"]+=[
 {"g":"hol","t":"Festival of Lights & Tree Lighting","w":"In front of Town Hall, Main St","p":"Santa, the high school choir and the Main Street lights switch on with the tree, the Friday after Thanksgiving at 6. This year's details aren't posted yet.","src":"https://danbury.macaronikid.com/events/6722d92a3487006b6b433163/ridgefields-annual-festival-of-lights-and-annual-tree-lighting"},
 {"g":"hw","t":"Halloween Kids' Night Out","w":"Boys & Girls Club, 41 Governor St","p":"A late-October Friday drop-off night with a Halloween parade and gym games. Last year it was Oct 24, 6:30–8:30 ($40 members). This year's date isn't posted yet.","src":"https://inridgefield.com/events/halloween-kids-night-out/"},
 {"g":"hol","t":"Library Days at Books on the Common","w":"Books on the Common, 404 Main St","p":"The Saturday after Thanksgiving, the bookstore donates 15% to the library for card holders and gives away a children's book every hour. Last year it was Nov 29, 10–3.","src":"https://patch.com/connecticut/ridgefield/calendar/event/20251129/6246ed89-4ec7-4044-91d4-e78d0e3e6e7d/library-days-at-books-on-the-common"},
]
TOWN["classes"]+=[
 {"id":"rf-glee-club","c":"music","n":"Glee Club (Parks & Rec)","u":"https://www.ridgefieldparksandrec.org/youth-courses/pages/glee-club","blurb":"Wednesday singing club, Sep 30–Dec 2. $163 members, $193 non-members.","ages":"Grades K–5","where":"Ridgefield Recreation Center"},
 {"id":"rf-build-it","c":"build","n":"Build It, Break It, Mold It, Make It","u":"https://www.ridgefieldparksandrec.org/youth-courses/pages/build-it-break-it-mold-it-make-it","blurb":"Monday hands-on engineering and making, Sep 28–Nov 30; a slime-and-science class follows in January.","ages":"Grades K–5","where":"Ridgefield Recreation Center"},
]
ES={
 "Free to visit; pumpkins priced individually":"Visita gratis; cada calabaza tiene su precio",
 "The church lawn fills with pumpkins on Main Street; pick one out and take photos. Open weekdays 2–6 and weekends 10–6.":"El jardín de la iglesia en Main Street se llena de calabazas; escoge una y toma fotos. Abre entre semana de 2 a 6 y los fines de semana de 10 a 6.",
 "A ranger tour of the farm's barns, farming history and artwork; meet at the Visitor Center sign.":"Un recorrido con un guardaparques por los graneros, la historia agrícola y el arte de la granja; reúnete en el letrero del Visitor Center.",
 "Grades K–5 + family":"Kínder–5.º grado + familia",
 "A school-holiday showing of Hocus Pocus; an adult must stay.":"Una función de Hocus Pocus en día feriado escolar; un adulto debe quedarse.",
 "Ages 10+ (under 14 with an adult)":"10 años o más (menores de 14 con un adulto)",
 "Tickets online":"Boletos en línea",
 "A 15–20 minute haunted trail walk after dark with live actors, run by the Ridgefield Fathers Club. Scary; best for older kids.":"Un recorrido embrujado de 15–20 minutos por un sendero de noche con actores en vivo, organizado por el Ridgefield Fathers Club. Da miedo; mejor para niños mayores.",
 "Drop in to meet Woodcock's animal ambassadors.":"Pasa a conocer a los animales embajadores de Woodcock.",
 "A ranger hike about trees and why leaves change color, then a leaf-print or landscape craft.":"Una caminata con un guardaparques sobre los árboles y por qué cambian de color las hojas, y luego una manualidad con hojas o paisajes.",
 "Ages 2–6 + caregiver":"2–6 años + un adulto",
 "$30 per child":"$30 por niño",
 "Hike in costume following animal clues, meet a tarantula and an albino snake, then hear a story. Bring a snack.":"Camina disfrazado siguiendo pistas de animales, conoce una tarántula y una serpiente albina, y escucha un cuento. Trae un bocadillo.",
 "Search the leaf litter for salamanders on a guided family hike.":"Busca salamandras entre las hojas en una caminata familiar guiada.",
 "Free (bring a food donation)":"Gratis (trae un alimento para donar)",
 "A big game of zombie tag hosted by Cub Scout Pack 116; bring a nonperishable food item.":"Un gran juego de 'zombie tag' organizado por el Cub Scout Pack 116; trae un alimento no perecedero.",
 "Come in costume to the one-room schoolhouse for treats and spooky local-history stories.":"Ven disfrazado a la escuelita de un salón por golosinas e historias locales de miedo.",
 "Halloween stories, then a costume parade around the library with goodie bags. Registration encouraged.":"Cuentos de Halloween y luego un desfile de disfraces alrededor de la biblioteca con bolsitas de dulces. Se recomienda inscribirse.",
 "Decorated trunks and treats outdoors at Lounsbury House on Halloween night.":"Cajuelas decoradas y dulces al aire libre en Lounsbury House la noche de Halloween.",
 "A short trail walk about fall nature, then a story.":"Una caminata corta por el sendero sobre la naturaleza en otoño, y luego un cuento.",
 "An Election Day open house: inflatables, Big Blue Blocks, recreation swim 2–4 and a pool slide (42-inch minimum) 2:30–3:30.":"Puertas abiertas en el Día de Elecciones: inflables, Big Blue Blocks, nado recreativo de 2 a 4 y un tobogán de alberca (estatura mínima de 42 pulgadas) de 2:30 a 3:30.",
 "A guided hike about how turtles and other animals get through a Connecticut winter.":"Una caminata guiada sobre cómo pasan el invierno de Connecticut las tortugas y otros animales.",
 "The town's ceremony with American Legion Post 78, with refreshments after.":"La ceremonia del pueblo con la American Legion Post 78, con refrigerios después.",
 "$35 members, $40 non-members":"$35 miembros, $40 no miembros",
 "Karaoke, dancing, crafts, pizza and popsicles; wear white or neon.":"Karaoke, baile, manualidades, pizza y paletas; vístete de blanco o neón.",
 "The First Selectman pardons 'Mr. Gobble'; meet the turkey and play lawn games. Rain or shine.":"El alcalde indulta a 'Mr. Gobble'; conoce al pavo y juega en el jardín. Con lluvia o sol.",
 "$22.95 (5K $38.96)":"$22.95 (5 km $38.96)",
 "The Boys & Girls Club's 45th Thanksgiving trot: a short kids' run at 8, then the 5K at 8:30. Prices go up after Oct 31.":"La 45.ª carrera de Acción de Gracias del Boys & Girls Club: una carrera corta para niños a las 8 y luego los 5 km a las 8:30. Los precios suben después del 31 de oct.",
 "During the Holiday Stroll: Santa and Mrs. Claus, live reindeer, selfies with elves and postcards for the troops.":"Durante el Holiday Stroll: Santa y la Sra. Claus, renos vivos, selfis con duendes y postales para las tropas.",
 "In front of Town Hall, Main St":"Frente al Ayuntamiento, Main St",
 "Santa, the high school choir and the Main Street lights switch on with the tree, the Friday after Thanksgiving at 6. This year's details aren't posted yet.":"Santa, el coro de la preparatoria y las luces de Main Street se encienden con el árbol, el viernes después de Acción de Gracias a las 6. Los detalles de este año aún no se han publicado.",
 "Boys & Girls Club, 41 Governor St":"Boys & Girls Club, 41 Governor St",
 "A late-October Friday drop-off night with a Halloween parade and gym games. Last year it was Oct 24, 6:30–8:30 ($40 members). This year's date isn't posted yet.":"Una noche sin papás un viernes de finales de octubre con desfile de Halloween y juegos en el gimnasio. El año pasado fue el 24 de oct., de 6:30 a 8:30 ($40 miembros). La fecha de este año aún no se ha publicado.",
 "Books on the Common, 404 Main St":"Books on the Common, 404 Main St",
 "The Saturday after Thanksgiving, the bookstore donates 15% to the library for card holders and gives away a children's book every hour. Last year it was Nov 29, 10–3.":"El sábado después de Acción de Gracias, la librería dona el 15% a la biblioteca por los titulares de credencial y regala un libro infantil cada hora. El año pasado fue el 29 de nov., de 10 a 3.",
 "Wednesday singing club, Sep 30–Dec 2. $163 members, $193 non-members.":"Club de canto los miércoles, del 30 de sept. al 2 de dic. $163 miembros, $193 no miembros.",
 "Monday hands-on engineering and making, Sep 28–Nov 30; a slime-and-science class follows in January.":"Ingeniería y creación práctica los lunes, del 28 de sept. al 30 de nov.; en enero sigue una clase de slime y ciencia.",
}
