W=lambda d,t:{"from":d,"t":t}
D=lambda ds,t:[W(d,t) for d in ds]
SRC="https://bportlibrary.libcal.com/"
B=["baby","toddler","preschool"]
MAIN,BR,NO,NF,BE="bpl-main","bpl-blackrock","bpl-north","bpl-newfield","bpl-beardsley"
def ev(v,**k):
    e={"v":v,"free":True,"price":"Free","src":SRC}; e.update(k); return e
TOWN={
 "display":"Bridgeport","accent":"#F5E1A4",
 "venues":{MAIN:["Burroughs-Saden Library (Main)","925 Broad St"],
           BR:["Black Rock Branch Library","2705 Fairfield Ave"],
           NO:["North Branch Library","3455 Madison Ave"],
           NF:["Newfield Branch Library","755 Central Ave"],
           BE:["Beardsley Branch Library","2536 East Main St"]},
 "venueMeta":{MAIN:["downtown",1],BR:["blackrock",1],NO:["northend",1],NF:["eastside",1],BE:["eastside",1]},
 "hoods":[["downtown","Downtown"],["blackrock","Black Rock"],["northend","North End"],["eastside","East Side"]],
 "events":[
  # ---- babies to preschool ----
  ev(NO,t="Playtime for Ages 0–5",s=[[1,[["10:30","11:15"]],"2026-10-12","2026-12-28"]],ages="Ages 0–5 + caregiver",a=B,drop=True,
     blurb="Free play with toys and music in the North Branch community room."),
  ev(NF,t="Little Readers Storytime",s=[[1,[["11:00","12:00"]],"2026-10-19","2026-12-28"]],ages="Up to age 5 + caregiver",a=B,drop=True,
     blurb="Stories, songs, dancing and a craft at the Newfield Branch."),
  ev(MAIN,t="Little Learners",s=[[2,[["11:00","12:00"]],"2026-10-13","2026-12-29"]],ages="Ages 0–5",a=B,drop=True,
     blurb="Stories, songs and early concepts like colors, shapes and numbers in the main library's Children's Room."),
  ev(BR,t="Wee Readers Story Time",s=[[3,[["11:00","11:30"]],"2026-10-14","2026-12-30"]],x=["2026-11-11"],
     when=D(["2026-10-10","2026-10-24","2026-11-07","2026-11-21","2026-12-05","2026-12-19"],[["11:00","11:30"]]),ages="Ages 0–5 + caregiver",a=B,rsvp=True,
     blurb="Stories and a craft at the Black Rock Branch, every Wednesday and every other Saturday. Registration requested."),
  ev(NO,t="Little Hands",s=[[3,[["11:00","12:00"]],"2026-10-14","2026-12-16"]],x=["2026-11-11"],ages="Ages 0–5 + caregiver",a=B,drop=True,
     blurb="An arts-and-crafts hour for little ones and their grown-ups at the North Branch."),
  ev(NO,t="Miss Claudia Sings a Story",s=[[4,[["11:00","11:45"]],"2026-10-08","2026-11-19"]],ages="Ages 0–5 + caregiver",a=B,drop=True,
     blurb="Music and a story with Miss Claudia at the North Branch. The posted series runs through Nov 19."),
  ev(NF,t="Music Together",s=[[4,[["13:00","14:00"]],"2026-10-08","2026-12-31"]],x=["2026-11-26"],ages="Babies to preschoolers + caregiver",a=B,drop=True,
     blurb="A free Music Together class of songs, rhythm and movement at the Newfield Branch."),
  ev(NO,t="Little Bears Story Time",s=[[5,[["11:00","11:45"]],"2026-10-09","2026-11-20"]],ages="Ages 0–5 + caregiver",a=B,drop=True,
     blurb="A drop-in storytime with songs and bubbles at the North Branch. The posted series runs through Nov 20."),
  ev(BE,t="Book Buddies Storytime",s=[[6,[["11:00","12:00"]],"2026-10-10","2026-12-19"]],x=["2026-11-28"],ages="Ages 2–6",a=["toddler","preschool"],drop=True,
     blurb="Saturday stories, songs, rhymes and a simple craft at the Beardsley Branch. No registration needed."),
  # ---- school-age ----
  ev(BR,t="Ms. Trina's Arts and Crafts",s=[[2,[["15:30","16:30"]],"2026-10-13","2026-12-29"]],ages="Ages 4 and up + caregiver",a=["preschool","big"],drop=True,
     blurb="A new take-home craft every Tuesday after school at the Black Rock Branch."),
  ev(NF,t="Lego Challenge",s=[[2,[["17:00","18:00"]],"2026-10-13","2026-12-29"]],ages="Ages 6–12",a=["big"],drop=True,
     blurb="Free building or engineering challenges with the Newfield Branch's LEGO."),
  ev(BE,t="Chess Club for Kids",s=[[1,[["16:00","17:30"]],"2026-10-19","2026-12-28"]],ages="Ages 6–16",a=["big"],drop=True,
     blurb="Chess strategy and problem-solving for beginners and experienced players at the Beardsley Branch."),
  ev(NF,t="Chess for Beginners",s=[[3,[["16:30","17:30"]],"2026-10-14","2026-12-30"]],x=["2026-11-11"],ages="Kids, teens and adults",a=["big"],drop=True,
     blurb="Learn the basics of chess at the Newfield Branch."),
  ev(MAIN,t="It's SlimeTime!",when=D(["2026-10-14","2026-10-21","2026-11-04","2026-11-18","2026-11-25","2026-12-02","2026-12-09","2026-12-16","2026-12-23","2026-12-30"],[["17:00","18:00"]]),ages="Ages 6–11",a=["big"],drop=True,
     blurb="Make slime with paint and glitter in the main library's Children's Room (Oct 21 is a 'Revenge of the Living Slime' special)."),
  ev(BR,t="STEAM Thursdays!",when=D(["2026-10-08","2026-10-22","2026-11-19","2026-12-03","2026-12-31"],[["16:00","17:00"]]),ages="Ages 8–12 (adult must attend)",a=["big"],rsvp=True,
     blurb="Hands-on art and science projects at the Black Rock Branch. Only 15 spots; registration strongly recommended."),
  ev(NO,t="Anime and Manga Club",when=D(["2026-10-08","2026-10-22","2026-11-05","2026-11-19"],[["16:30","17:45"]]),ages="Ages 9–13",a=["big"],drop=True,
     blurb="Talk anime and manga, make crafts and get reading recommendations at the North Branch."),
  ev(NO,t="Pokémon Club",when=D(["2026-10-15","2026-10-29","2026-11-12"],[["16:30","17:30"]]),ages="Ages 5–14",a=["big"],drop=True,
     blurb="Pokémon card games and activities at the North Branch."),
  ev(BR,t="Family Movies!",when=D(["2026-10-10","2026-10-24","2026-11-07","2026-11-21","2026-12-05","2026-12-19"],[["13:00","14:30"]]),ages="Kids + caregivers",a=["preschool","big"],drop=True,
     blurb="A family movie with snacks at the Black Rock Branch, every other Saturday."),
  ev(BR,t="Saturday Crafternoons",when=D(["2026-10-10","2026-10-24","2026-11-07","2026-11-21","2026-12-05","2026-12-19"],[["15:00","16:00"]]),ages="Ages 4 and up + caregiver",a=["preschool","big"],drop=True,
     blurb="Drop-in crafts at the Black Rock Branch after the family movie."),
  ev(BR,t="Black Rock Lego Club",when=D(["2026-10-17","2026-10-31","2026-11-14","2026-12-12"],[["15:00","16:00"]]),ages="Ages 4 and up + caregiver",a=["preschool","big"],drop=True,
     blurb="Free building with the library's LEGO at the Black Rock Branch."),
  ev(BE,t="Microbit Robotics",when=D(["2026-10-14","2026-11-18","2026-12-16"],[["16:00","17:30"]]),ages="Ages 8–15",a=["big"],drop=True,
     blurb="Code and build Micro:bit robots and remote-control cars at the Beardsley Branch."),
  ev(BE,t="Kids Book Club: Books-in-Between",when=D(["2026-10-20","2026-11-17","2026-12-15"],[["18:00","19:00"]]),ages="Grades 4–6",a=["big"],check=True,
     blurb="A monthly book club at the Beardsley Branch: Witches of Brooklyn (Oct), Walls Within Walls (Nov) and The Silver Arrow (Dec)."),
  # ---- one-offs ----
  ev(MAIN,t="Edible Witch Hat!",special="hw",when=[W("2026-10-10",[["11:00","13:00"]])],ages="Ages 5–12",a=["big"],drop=True,
     blurb="Make a Halloween witch hat you can eat."),
  ev(MAIN,t="Touch-A-Truck: Fire Prevention Month",when=[W("2026-10-14",[["14:30","15:30"]])],ages="Ages 3–12",a=["preschool","big"],drop=True,
     blurb="A fire-safety storytime, then a visit from a real fire truck."),
  ev(BR,t="Christine's Critters: Owls and Other Birds",when=[W("2026-10-15",[["18:00","19:00"]])],ages="Kids, teens and caregivers",a=["preschool","big"],rsvp=True,
     blurb="Meet live owls and other birds and learn how they live. Registration requested."),
  ev(BE,t="Curious Creatures at the Library",when=[W("2026-10-17",[["14:00","15:00"]])],ages="All ages",a=B+["big"],drop=True,
     blurb="A live-animal visit with reptiles and other creatures."),
  ev(NF,t="Indoor Halloween Campout",special="hw",when=[W("2026-10-21",[["17:00","18:30"]])],ages="Ages 6–12 and teens",a=["big"],drop=True,
     blurb="Come in pajamas or a costume for spooky stories and treats at an indoor 'campout.'"),
  ev(NF,t="Saturday Slime Lab: Magnetic Slime",when=[W("2026-10-24",[["15:00","16:00"]])],ages="Ages 6 and up",a=["big"],drop=True,
     blurb="Make slime that moves with a magnet."),
  ev(NF,t="Sugar Skull Paint Craft",special="hw",when=[W("2026-10-26",[["16:00","17:00"]])],ages="Ages 6–11",a=["big"],drop=True,
     blurb="Paint and decorate a sugar skull for Día de los Muertos."),
  ev(MAIN,t="Halloween Storytime & Bingo!",special="hw",when=[W("2026-10-27",[["16:30","17:30"]])],ages="Ages 3–12",a=["preschool","big"],drop=True,
     blurb="Not-too-spooky Halloween stories and a round of bingo."),
  ev(MAIN,t="Spooktacular Fun @ the Library!",special="hw",when=[W("2026-10-28",[["16:30","19:00"]])],ages="Ages 0–12",a=B+["big"],drop=True,
     blurb="A Halloween party at the main library with a costume parade, games and crafts."),
  ev(BR,t="Halloween Spooky Spree!",special="hw",when=[W("2026-10-29",[["18:00","19:15"]])],ages="Under 12 + caregiver",a=B+["big"],rsvp=True,
     blurb="A short movie, then pumpkin painting and refreshments. Registration strongly encouraged."),
  ev(BE,t="Halloween Storytime & Pumpkin Decorating",special="hw",when=[W("2026-10-31",[["14:00","15:15"]])],ages="Ages 2–12",a=["toddler","preschool","big"],drop=True,
     blurb="A costume storytime, spooky crafts, a scavenger hunt, pumpkin decorating and treats."),
  ev(BR,t="Living Dragons with Riverside Reptiles",when=[W("2026-11-03",[["17:00","18:00"]])],ages="All ages",a=B+["big"],rsvp=True,
     blurb="Meet live lizards up close on the Election Day school holiday. Registration requested."),
 ],
 "tba":[
  {"g":"hw","t":"Boo at the Zoo","w":"Connecticut's Beardsley Zoo, 1875 Noble Ave",
   "p":"The zoo's Halloween day, usually a Sunday in late October, 11 to 3, with costumes, story times, animal meet-and-greets and treats. This year's date isn't posted yet.","src":"https://beardsleyzoo.org/about-us/press/connecticuts-beardsley-zoo-hosts-boo-at-the-zoo-for-kids-of-all-ages/"},
  {"g":"hol","t":"Bridgeport Tree Lighting","w":"McLevy Green, downtown",
   "p":"The city lights its tree on McLevy Green in late November or early December, with performances, vendors and food trucks. This year's date isn't posted yet.","src":"https://www.bridgeportct.gov/events/mayor-ganim-and-city-bridgeports-annual-tree-lighting"},
 ],
 "classes":[],
 "library":{"for":"Free, every week","name":"Bridgeport Public Library","desc":"Five branches with something almost every day: baby and toddler storytimes, playtime and Music Together in the mornings, and after-school LEGO, chess, slime, crafts and robotics. Most programs are drop-in.","a":"See the library's calendar","href":SRC},
}
PLACES={
 "out":[("Connecticut's Beardsley Zoo","Connecticut's only zoo, with a rainforest building, a farmyard and a carousel. Open daily 9–4.","El único zoológico de Connecticut, con un edificio de selva tropical, una granja y un carrusel. Abre todos los días de 9 a 4."),
        ("Beardsley Park","A big Olmsted-designed park next to the zoo, with a pond, playground and walking paths.","Un gran parque diseñado por Olmsted junto al zoológico, con estanque, área de juegos y senderos."),
        ("Seaside Park","A long city beach and park on Long Island Sound, with playgrounds and a walk out toward Fayerweather Island's lighthouse.","Una larga playa y parque de la ciudad en el estrecho de Long Island, con áreas de juegos y un camino hacia el faro de Fayerweather Island.")],
 "rain":[("Discovery Museum","Hands-on science exhibits and a planetarium. Free Wednesdays for Bridgeport residents with ID; open until 7 on Wednesdays.","Exposiciones de ciencia interactivas y un planetario. Gratis los miércoles para residentes de Bridgeport con identificación; abre hasta las 7 los miércoles."),
         ("Bridgeport Public Library","Five branches with daily baby and toddler programs and after-school clubs; Black Rock and North are the busiest for little ones.","Cinco sucursales con programas diarios para bebés y niños pequeños y clubes después de clases; Black Rock y North son las más activas para los más pequeños."),
         ("Wonderland of Ice","An indoor ice rink with public skating sessions; check the rink's schedule before you go.","Una pista de hielo techada con sesiones de patinaje público; consulta el horario antes de ir.")],
 "drive":[("Boothe Memorial Park","Free gardens, a playground and quirky historic buildings in Stratford.","Jardines gratis, un área de juegos y curiosos edificios históricos en Stratford."),
          ("Connecticut Audubon Birdcraft Museum","A small nature museum and bird sanctuary in Fairfield.","Un pequeño museo de naturaleza y santuario de aves en Fairfield."),
          ("Silverman's Farm","Pick-your-own apples and pumpkins, an animal farm and a farm market in Easton.","Manzanas y calabazas para cosechar, una granja de animales y un mercado en Easton.")],
}
ES={
 "Ages 0–5 + caregiver":"0–5 años + un adulto",
 "Free play with toys and music in the North Branch community room.":"Juego libre con juguetes y música en el salón comunitario de la sucursal North.",
 "Up to age 5 + caregiver":"Hasta 5 años + un adulto",
 "Stories, songs, dancing and a craft at the Newfield Branch.":"Cuentos, canciones, baile y una manualidad en la sucursal Newfield.",
 "Ages 0–5":"0–5 años",
 "Stories, songs and early concepts like colors, shapes and numbers in the main library's Children's Room.":"Cuentos, canciones y conceptos básicos como colores, formas y números en la sala infantil de la biblioteca principal.",
 "Stories and a craft at the Black Rock Branch, every Wednesday and every other Saturday. Registration requested.":"Cuentos y una manualidad en la sucursal Black Rock, todos los miércoles y un sábado sí y otro no. Se pide inscripción.",
 "An arts-and-crafts hour for little ones and their grown-ups at the North Branch.":"Una hora de arte y manualidades para los pequeños y sus adultos en la sucursal North.",
 "Music and a story with Miss Claudia at the North Branch. The posted series runs through Nov 19.":"Música y un cuento con Miss Claudia en la sucursal North. La serie publicada llega hasta el 19 de nov.",
 "Babies to preschoolers + caregiver":"Bebés a preescolares + un adulto",
 "A free Music Together class of songs, rhythm and movement at the Newfield Branch.":"Una clase gratis de Music Together con canciones, ritmo y movimiento en la sucursal Newfield.",
 "A drop-in storytime with songs and bubbles at the North Branch. The posted series runs through Nov 20.":"Un cuentacuentos sin inscripción con canciones y burbujas en la sucursal North. La serie publicada llega hasta el 20 de nov.",
 "Ages 2–6":"2–6 años",
 "Saturday stories, songs, rhymes and a simple craft at the Beardsley Branch. No registration needed.":"Cuentos, canciones, rimas y una manualidad sencilla los sábados en la sucursal Beardsley. No hace falta inscribirse.",
 "Ages 4 and up + caregiver":"Desde 4 años + un adulto",
 "A new take-home craft every Tuesday after school at the Black Rock Branch.":"Una manualidad nueva para llevar a casa cada martes después de clases en la sucursal Black Rock.",
 "Ages 6–12":"6–12 años",
 "Free building or engineering challenges with the Newfield Branch's LEGO.":"Construcción libre o retos de ingeniería con los LEGO de la sucursal Newfield.",
 "Ages 6–16":"6–16 años",
 "Chess strategy and problem-solving for beginners and experienced players at the Beardsley Branch.":"Estrategia de ajedrez y resolución de problemas para principiantes y jugadores con experiencia en la sucursal Beardsley.",
 "Kids, teens and adults":"Niños, adolescentes y adultos",
 "Learn the basics of chess at the Newfield Branch.":"Aprende lo básico del ajedrez en la sucursal Newfield.",
 "Ages 6–11":"6–11 años",
 "Make slime with paint and glitter in the main library's Children's Room (Oct 21 is a 'Revenge of the Living Slime' special).":"Haz slime con pintura y brillantina en la sala infantil de la biblioteca principal (el 21 de oct. es una edición especial 'Revenge of the Living Slime').",
 "Ages 8–12 (adult must attend)":"8–12 años (con un adulto)",
 "Hands-on art and science projects at the Black Rock Branch. Only 15 spots; registration strongly recommended.":"Proyectos prácticos de arte y ciencia en la sucursal Black Rock. Solo 15 lugares; se recomienda mucho inscribirse.",
 "Ages 9–13":"9–13 años",
 "Talk anime and manga, make crafts and get reading recommendations at the North Branch.":"Habla de anime y manga, haz manualidades y recibe recomendaciones de lectura en la sucursal North.",
 "Ages 5–14":"5–14 años",
 "Pokémon card games and activities at the North Branch.":"Juegos de cartas y actividades de Pokémon en la sucursal North.",
 "Kids + caregivers":"Niños + adultos",
 "A family movie with snacks at the Black Rock Branch, every other Saturday.":"Una película familiar con bocadillos en la sucursal Black Rock, un sábado sí y otro no.",
 "Drop-in crafts at the Black Rock Branch after the family movie.":"Manualidades sin inscripción en la sucursal Black Rock después de la película familiar.",
 "Free building with the library's LEGO at the Black Rock Branch.":"Construcción libre con los LEGO de la biblioteca en la sucursal Black Rock.",
 "Ages 8–15":"8–15 años",
 "Code and build Micro:bit robots and remote-control cars at the Beardsley Branch.":"Programa y construye robots Micro:bit y autos a control remoto en la sucursal Beardsley.",
 "Grades 4–6":"4.º a 6.º grado",
 "A monthly book club at the Beardsley Branch: Witches of Brooklyn (Oct), Walls Within Walls (Nov) and The Silver Arrow (Dec).":"Un club de lectura mensual en la sucursal Beardsley: Witches of Brooklyn (oct.), Walls Within Walls (nov.) y The Silver Arrow (dic.).",
 "Ages 5–12":"5–12 años",
 "Make a Halloween witch hat you can eat.":"Haz un sombrero de bruja de Halloween que se puede comer.",
 "Ages 3–12":"3–12 años",
 "A fire-safety storytime, then a visit from a real fire truck.":"Un cuentacuentos sobre seguridad contra incendios y luego la visita de un camión de bomberos de verdad.",
 "Kids, teens and caregivers":"Niños, adolescentes y adultos",
 "Meet live owls and other birds and learn how they live. Registration requested.":"Conoce búhos y otras aves vivas y aprende cómo viven. Se pide inscripción.",
 "All ages":"Todas las edades",
 "A live-animal visit with reptiles and other creatures.":"Una visita de animales vivos con reptiles y otras criaturas.",
 "Ages 6–12 and teens":"6–12 años y adolescentes",
 "Come in pajamas or a costume for spooky stories and treats at an indoor 'campout.'":"Ven en pijama o disfrazado a un 'campamento' bajo techo con cuentos de miedo y dulces.",
 "Ages 6 and up":"Desde 6 años",
 "Make slime that moves with a magnet.":"Haz slime que se mueve con un imán.",
 "Paint and decorate a sugar skull for Día de los Muertos.":"Pinta y decora una calavera de azúcar para el Día de los Muertos.",
 "Not-too-spooky Halloween stories and a round of bingo.":"Cuentos de Halloween que no dan mucho miedo y una partida de bingo.",
 "Ages 0–12":"0–12 años",
 "A Halloween party at the main library with a costume parade, games and crafts.":"Una fiesta de Halloween en la biblioteca principal con desfile de disfraces, juegos y manualidades.",
 "Under 12 + caregiver":"Menores de 12 años + un adulto",
 "A short movie, then pumpkin painting and refreshments. Registration strongly encouraged.":"Una película corta, luego pintura de calabazas y refrigerios. Se recomienda mucho inscribirse.",
 "Ages 2–12":"2–12 años",
 "A costume storytime, spooky crafts, a scavenger hunt, pumpkin decorating and treats.":"Un cuentacuentos con disfraces, manualidades de miedo, una búsqueda del tesoro, decoración de calabazas y dulces.",
 "Meet live lizards up close on the Election Day school holiday. Registration requested.":"Conoce lagartijas vivas de cerca el día sin clases de las elecciones. Se pide inscripción.",
 "The zoo's Halloween day, usually a Sunday in late October, 11 to 3, with costumes, story times, animal meet-and-greets and treats. This year's date isn't posted yet.":"El día de Halloween del zoológico, normalmente un domingo a finales de octubre, de 11 a 3, con disfraces, cuentacuentos, encuentros con animales y dulces. La fecha de este año aún no se ha publicado.",
 "Connecticut's Beardsley Zoo, 1875 Noble Ave":"Connecticut's Beardsley Zoo, 1875 Noble Ave",
 "The city lights its tree on McLevy Green in late November or early December, with performances, vendors and food trucks. This year's date isn't posted yet.":"La ciudad enciende su árbol en McLevy Green a finales de noviembre o principios de diciembre, con presentaciones, vendedores y camiones de comida. La fecha de este año aún no se ha publicado.",
 "McLevy Green, downtown":"McLevy Green, en el centro",
 "Five branches with something almost every day: baby and toddler storytimes, playtime and Music Together in the mornings, and after-school LEGO, chess, slime, crafts and robotics. Most programs are drop-in.":"Cinco sucursales con algo casi todos los días: cuentacuentos para bebés y niños pequeños, juego libre y Music Together por las mañanas, y LEGO, ajedrez, slime, manualidades y robótica después de clases. La mayoría de los programas no requieren inscripción.",
 "Free":"Gratis",
}

# ---- Full playbook pass (Oct 7) ----
ZOO="beardsley-zoo"; DSC="discovery"
TOWN["venues"].update({ZOO:["Connecticut's Beardsley Zoo","1875 Noble Ave"],DSC:["SHU Discovery Science Center & Planetarium","4450 Park Ave"]})
TOWN["venueMeta"].update({ZOO:["eastside",0],DSC:["northend",1]})
GW=[[d,[["17:30","21:30"]],"2026-10-08","2026-12-20"] for d in (4,5,6,0)]
TOWN["events"]+=[
 {"t":"GLOW Wild","v":ZOO,"special":"fall","s":GW,"x":["2026-11-26"],"ages":"All ages","a":B+["big"],"free":False,"price":"Timed tickets; buy online","rsvp":True,"src":"https://beardsleyzoo.org/events/glow-wild-5bvj3p/",
  "blurb":"An evening walk through the zoo lit by giant animal lanterns, Thursday–Sunday nights through Dec 20. Buy timed tickets online in advance."},
 {"t":"Trick or Treat Fest at the Discovery Museum","v":DSC,"special":"hw","when":[W("2026-10-17",[["10:00","14:00"]])],"ages":"All ages","a":B+["big"],"free":False,"price":"$10","src":"https://ctvisit.com/events/trick-or-treat-fest-discovery-museum",
  "blurb":"Come in costume for a Candy Trail, crafts, costumed characters, stage shows and Halloween games."},
 {"t":"Thankful Friday","v":DSC,"special":"hol","when":[W("2026-11-27",[["10:00","16:00"]])],"ages":"Families","a":B+["big"],"free":True,"price":"Free admission (last year)","check":True,"src":"https://www.shudiscovery.org/event-details/thankful-friday-1",
  "blurb":"The day after Thanksgiving: make gifts, take family photos and meet Santa. Bring a new, unwrapped toy for the toy drive. Details are from last year; check before you go."},
]
TOWN["classes"]+=[
 {"id":"wonderland-ice","c":"move","n":"Wonderland of Ice skating classes","u":"https://mommypoppins.com/kids/ice-skating-lessons-in-fairfield-county",
  "blurb":"Year-round small-group skating classes (eight skaters max), from a tot program at age 3 to micro hockey and Theater on Ice, plus public skating.","ages":"3 and up","where":"Glenwood Ave, by Beardsley Park"},
 {"id":"cabaret-childrens","c":"art","n":"Cabaret Children's Theatre (Downtown Cabaret)","u":"https://dtcab.com/bridgeport-theatre-co-dct",
  "blurb":"Downtown Cabaret Theatre's long-running professional children's theatre company, with family shows and youth auditions; check the season schedule.","ages":"Kids","where":"Downtown Bridgeport"},
]
PLACES["rain"]=[p for p in PLACES["rain"] if p[0]!="Discovery Museum"]
PLACES["rain"].insert(0,("SHU Discovery Science Center & Planetarium","Sacred Heart University's hands-on science center and planetarium (formerly the Discovery Museum). Free on Wednesdays for Bridgeport residents with ID, when it's open until 7 (4450 Park Ave).","El centro de ciencia interactivo y planetario de Sacred Heart University (antes Discovery Museum). Gratis los miércoles para residentes de Bridgeport con identificación, cuando abre hasta las 7 (4450 Park Ave)."))
PLACES["rain"]+=[("Black Rock Books","An independent bookstore in Black Rock with a children's section (3030 Fairfield Ave).","Una librería independiente en Black Rock con sección infantil (3030 Fairfield Ave)."),
                 ("Kindred Thoughts Bookstore","A Black-owned bookstore downtown featuring African American literature, including books for kids (1001 Main St).","Una librería afroamericana en el centro especializada en literatura afroamericana, con libros para niños (1001 Main St).")]
ES.update({
 "Timed tickets; buy online":"Boletos con horario; cómpralos en línea",
 "An evening walk through the zoo lit by giant animal lanterns, Thursday–Sunday nights through Dec 20. Buy timed tickets online in advance.":"Un paseo nocturno por el zoológico iluminado con faroles gigantes de animales, de jueves a domingo por la noche hasta el 20 de dic. Compra boletos con horario en línea por adelantado.",
 "$10":"$10",
 "Come in costume for a Candy Trail, crafts, costumed characters, stage shows and Halloween games.":"Ven disfrazado: sendero de dulces, manualidades, personajes disfrazados, espectáculos y juegos de Halloween.",
 "Families":"Familias",
 "Free admission (last year)":"Entrada gratis (el año pasado)",
 "The day after Thanksgiving: make gifts, take family photos and meet Santa. Bring a new, unwrapped toy for the toy drive. Details are from last year; check before you go.":"El día después de Acción de Gracias: haz regalos, tómate fotos en familia y conoce a Santa. Trae un juguete nuevo sin envolver para la colecta. Los detalles son del año pasado; confirma antes de ir.",
 "Year-round small-group skating classes (eight skaters max), from a tot program at age 3 to micro hockey and Theater on Ice, plus public skating.":"Clases de patinaje en grupos pequeños todo el año (máximo ocho patinadores), desde un programa para niños de 3 años hasta micro hockey y Theater on Ice, además de patinaje público.",
 "3 and up":"Desde 3 años",
 "Glenwood Ave, by Beardsley Park":"Glenwood Ave, junto a Beardsley Park",
 "Downtown Cabaret Theatre's long-running professional children's theatre company, with family shows and youth auditions; check the season schedule.":"La veterana compañía profesional de teatro infantil del Downtown Cabaret Theatre, con funciones familiares y audiciones juveniles; consulta la programación de la temporada.",
 "Kids":"Niños",
 "Downtown Bridgeport":"Centro de Bridgeport",
})

# ---- gap check (Oct 7) ----
PLACES["out"]+=[("City splash pads","Bridgeport Parks & Recreation runs 15 free summer splash pads, including Beardsley Park, Seaside Park (West Beach), Newfield Park, Puglio Park and Went Field Park.","Bridgeport Parks & Recreation administra 15 zonas de chorros de agua gratis en verano, como Beardsley Park, Seaside Park (West Beach), Newfield Park, Puglio Park y Went Field Park.")]

# ---- creative places / bookstores / blogs pass (Oct 8) ----
PLACES["out"]+=[("Captain's Cove Seaport","A free waterfront boardwalk and marina on Black Rock Harbor for a walk and boat-watching (1 Bostwick Ave).","Un malecón y puerto deportivo gratis en Black Rock Harbor para caminar y ver barcos (1 Bostwick Ave).")]
