W=lambda d,t:{"from":d,"t":t}
D=lambda ds,t:[W(d,t) for d in ds]
L="scranton-library"; SRC="https://scranton.librarycalendar.com/events/upcoming"
B=["baby","toddler","preschool"]
def ev(**k):
    e={"v":L,"free":True,"price":"Free","src":SRC}; e.update(k); return e
T1=[["10:00","10:30"]]
TOWN={
 "display":"Madison","accent":"#C7E3C0",
 "venues":{L:["E.C. Scranton Memorial Library","801 Boston Post Rd"],"madison-green":["Madison Town Green","Boston Post Rd"]},
 "venueMeta":{L:[None,1],"madison-green":[None,0]},
 "events":[
  ev(t="Itty Bitty Meetup",s=[[1,[["10:30","11:30"]],"2026-10-05","2026-12-28"],[2,[["10:30","11:30"]],"2026-10-06","2026-12-29"],[3,[["10:30","11:30"]],"2026-10-07","2026-12-30"],[6,[["09:30","10:30"]],"2026-10-10","2026-12-19"]],
     x=["2026-10-12","2026-11-11"],ages="Babies to preschoolers + caregiver",a=B,drop=True,
     blurb="Meet other parents and caregivers while babies, toddlers and preschoolers play and make friends in the Children's Library."),
  ev(t="Walkers & Wigglers",when=D(["2026-10-05","2026-10-26","2026-11-02","2026-11-09","2026-11-30"],T1),ages="Walking toddlers (1 and up) + caregiver",a=["toddler"],rsvp=True,
     blurb="A storytime for toddlers on the move, with music, movement, rhymes and stories."),
  ev(t="Toddler Tango",when=D(["2026-10-06","2026-10-13","2026-10-27","2026-11-03","2026-11-10"],T1),ages="Ages 1–3 + caregiver",a=["toddler"],rsvp=True,
     blurb="A 30-minute music-and-movement class to rock out with your toddler. Registration recommended; limited walk-in spots."),
  ev(t="Tots & Tales",when=[W("2026-10-07",T1),W("2026-10-14",[["10:30","11:00"]]),W("2026-10-28",T1),W("2026-11-04",T1)],ages="Birth–age 2 + caregiver",a=["baby","toddler"],rsvp=True,
     blurb="A storytime for babies and toddlers of all abilities, with music, movement, rhymes and stories."),
  ev(t="Mini Bookworms",when=D(["2026-10-08","2026-11-12"],[["10:00","10:45"]]),ages="Birth–age 2 + caregiver",a=["baby","toddler"],rsvp=True,
     blurb="Books and songs, then a simple craft or toy play for babies and toddlers."),
  ev(t="Storytime Sprouts",when=D(["2026-10-09","2026-10-16","2026-11-13"],T1),ages="Ages 1–4 + caregiver",a=["toddler","preschool"],rsvp=True,
     blurb="Stories, songs, rhymes and movement for budding bookworms."),
  ev(t="Baby & Me Yoga",when=[W("2026-10-22",T1),W("2026-11-17",[["10:15","10:45"]])],ages="Babies + caregiver",a=["baby"],rsvp=True,
     blurb="Gentle yoga poses for bonding time with your baby. Registration required."),
  ev(t="Toddler Yoga",when=D(["2026-10-23","2026-11-20"],[["11:00","11:30"]]),ages="Ages 2–4 + caregiver",a=["toddler","preschool"],rsvp=True,
     blurb="Gentle yoga and movement for you and your toddler. Bring a yoga mat; space is limited."),
  ev(t="Book Buds",when=D(["2026-10-05","2026-10-19","2026-10-26"],[["16:45","17:30"]]),ages="Kids",a=["big"],check=True,
     blurb="A fall program run by the library's teen and children's departments. Check with the library for details and sign-up."),
  ev(t="Art with Kristin",when=D(["2026-10-07","2026-10-14","2026-11-12","2026-11-18"],[["16:30","17:30"]]),ages="Ages 5–8 or 8–12 (varies)",a=["big"],rsvp=True,
     blurb="A new monthly art project with Kristin Cafferty: a castle (Oct 7, ages 5–8), a neon skull (Oct 14, ages 8–12), 3-D hot cocoa (Nov 12, ages 5–8) and a city perspective (Nov 18, ages 8–12). Registration required."),
  ev(t="The Young Artist Workshop Series",when=D(["2026-10-08","2026-10-15","2026-10-22","2026-10-29"],[["16:30","17:30"]]),ages="Grades K–5",a=["big"],rsvp=True,check=True,
     blurb="A four-part art series with multi-day projects. Currently full; check for openings."),
  ev(t="How to Draw Spooky Halloween Monsters",special="hw",when=[W("2026-10-13",[["16:30","17:30"]])],ages="Grades K–5",a=["big"],rsvp=True,
     blurb="Learn to draw Halloween monsters for spooky season. Registration required."),
  ev(t="The Day the Crayons Quit (live show)",special="shows",when=[W("2026-10-21",[["16:00","16:15"]]),W("2026-10-29",[["10:00","10:15"]])],ages="Kids of all ages",a=B+["big"],rsvp=True,
     blurb="The Grove School Theater Troupe brings the picture book to life in a short live performance. Registration recommended."),
  ev(t="LEGO Mural Grand Opening",when=[W("2026-10-23",[["16:00","17:00"]])],ages="All ages",a=B+["big"],drop=True,
     blurb="See the unveiling of a new mural made of hundreds of LEGO pieces, created as a fundraiser for the CT Cancer Foundation."),
  ev(t="Annual Spooky Graham Cracker Houses",special="hw",when=[W("2026-10-24",[["10:30","11:30"]])],ages="Preschool–grade 5",a=["preschool","big"],rsvp=True,
     blurb="Build a spooky graham-cracker house. Each registration is one house, so sign up each child separately; arrive within 15 minutes of the start."),
  ev(t="Cozy Craft",when=D(["2026-10-24","2026-11-21"],[["13:00","16:00"]]),ages="All ages",a=["preschool","big"],drop=True,
     blurb="Swing by to put together a simple printable craft: a magnetic crow (Oct 24) or a silly dove (Nov 21)."),
  ev(t="Spooky Spiders",special="hw",when=[W("2026-10-28",[["16:15","17:00"]])],ages="Ages 5 and up",a=["big"],rsvp=True,
     blurb="Paint a spider and weave its web in the Children's Room. Registration required."),
  ev(t="Halloween Storytime and Costume Parade",special="hw",when=[W("2026-10-30",[["10:00","11:30"]])],ages="Babies and kids of all ages",a=B+["big"],rsvp=True,
     blurb="A Halloween storytime, then a costume parade down the main hallway and a treat from the treasure chest."),
  {"t":"Trunk or Treat on the Green","v":"madison-green","special":"hw","when":[W("2026-10-31",[["16:00","18:00"]])],"ages":"All ages","a":B+["big"],"free":True,"price":"Free","drop":True,"check":True,
   "blurb":"Halloween trunk-or-treating on the Madison Green. The Scranton Library will be there in costume with candy and program info.","src":SRC},
  ev(t="Aroma Therapy Jars",when=[W("2026-11-02",[["16:00","16:45"]])],ages="Ages 5 and up",a=["big"],rsvp=True,
     blurb="Make a decorative jar filled with the scents of autumn. Registration required."),
  ev(t="All About Opossums",when=[W("2026-11-03",[["14:00","15:00"]])],ages="Kids and teens",a=["big"],rsvp=True,
     blurb="Spend the Election Day school holiday meeting and learning about opossums. Registration required."),
  ev(t="Cool Catapults: Levers and Launchers",when=[W("2026-11-04",[["16:30","17:15"]])],ages="Ages 6–11",a=["big"],rsvp=True,
     blurb="Explore the physics of simple machines by building working launchers."),
  ev(t="Intro to Junk Journaling",when=[W("2026-11-05",[["17:30","18:15"]])],ages="Grades K–5",a=["big"],rsvp=True,
     blurb="Turn ticket stubs, photos and other keepsakes into a handmade journal."),
  ev(t="Twinkletoes Music",when=[W("2026-11-06",T1)],ages="Babies to preschoolers",a=B,rsvp=True,
     blurb="Play xylophones, maracas and drums, then march, skip and gallop with ribbons and a parachute."),
  ev(t="Bubbles & Parachute: Pop Girlies Edition",when=[W("2026-11-07",T1)],ages="Ages 1–5",a=["toddler","preschool"],rsvp=True,
     blurb="Half bubbles, half parachute play to songs by the biggest female pop stars of the 1980s through 2010s."),
  ev(t="Taylor Swift Party",when=[W("2026-11-10",[["16:00","16:45"]])],ages="Kids of all ages",a=B+["big"],rsvp=True,
     blurb="Shake it off with music, crafts and other Swiftie fun."),
  ev(t="Find Your Dinosaur ROAR!",special="shows",when=[W("2026-11-14",[["10:00","10:45"]])],ages="Babies through grade 3",a=B+["big"],rsvp=True,
     blurb="Stomp, dance and sing along with Michele Urban in a family music program."),
  ev(t="Seasonal Storytime and Craft",when=[W("2026-11-19",[["10:00","10:45"]])],ages="Ages 2–6",a=["toddler","preschool"],rsvp=True,
     blurb="Mr. Neil reads The Leaf Thief by Alice Hemming, then kids make a fall squirrel craft."),
  ev(t="Tween Afternoon",when=[W("2026-11-28",[["14:00","15:00"]])],ages="Grades 4 and up",a=["big"],rsvp=True,
     blurb="Video games, crafts and snacks for tweens over Thanksgiving weekend. Registration recommended."),
 ],
 "tba":[{"g":"hol","t":"Madison Holiday Tree Lighting","w":"Madison Town Green",
   "p":"Madison lights its tree on the Green in early December, usually a Friday evening around 6 pm, with Santa and music. This year's date isn't posted yet.","src":"https://www.madisonct.org/"}],
 "classes":[],
 "library":{"for":"Free, every week","name":"E.C. Scranton Memorial Library","desc":"A drop-in Itty Bitty Meetup four days a week, a rotating lineup of baby and toddler storytimes, music and yoga, monthly art with Kristin, and free weekly craft kits from the 'library faerie.'","a":"See the library's calendar","href":SRC},
}
PLACES={
 "out":[("Hammonasset Beach State Park","Connecticut's longest public beach, with a boardwalk, picnic areas and the Meigs Point Nature Center's touch tanks and trails.","La playa pública más larga de Connecticut, con malecón, áreas de picnic y los tanques táctiles y senderos del Meigs Point Nature Center."),
        ("Madison Town Green","The historic green in the center of town, home to the Halloween trunk-or-treat and the holiday tree lighting.","El histórico parque central del pueblo, donde se celebran el trunk-or-treat de Halloween y el encendido del árbol navideño."),
        ("Bauer Park","A town park with walking paths, gardens and open fields.","Un parque del pueblo con senderos para caminar, huertos y campos abiertos.")],
 "rain":[("E.C. Scranton Memorial Library","A busy children's library with storytimes, music, yoga, art classes and free craft kits.","Una biblioteca infantil muy activa con cuentacuentos, música, yoga, clases de arte y kits de manualidades gratis."),
         ("R.J. Julia Booksellers","A beloved independent bookstore on Boston Post Road with a big children's section and author events.","Una querida librería independiente en Boston Post Road con una gran sección infantil y eventos con autores."),
         ("Madison Historical Society","Keeps the Allis-Bushnell House and local history exhibits; check open hours and events.","Cuida la casa Allis-Bushnell y exposiciones de historia local; consulta horarios y eventos.")],
 "drive":[("Bishop's Orchards","Pick-your-own fruit, pumpkins, a farm market and creamery in Guilford.","Frutas para cosechar, calabazas, mercado y heladería en Guilford."),
          ("Essex Steam Train & Riverboat","Vintage steam-train rides along the Connecticut River, including the holiday North Pole Express.","Paseos en tren de vapor antiguo junto al río Connecticut, incluido el North Pole Express navideño."),
          ("Lyman Orchards","Pick-your-own apples and pumpkins, a corn maze and fall weekend activities in Middlefield.","Manzanas y calabazas para cosechar, laberinto de maíz y actividades de fin de semana en otoño en Middlefield.")],
}
ES={
 "Meet other parents and caregivers while babies, toddlers and preschoolers play and make friends in the Children's Library.":"Conoce a otros padres y cuidadores mientras bebés, niños pequeños y preescolares juegan y hacen amigos en la biblioteca infantil.",
 "Babies to preschoolers + caregiver":"Bebés a preescolares + un adulto",
 "A storytime for toddlers on the move, with music, movement, rhymes and stories.":"Un cuentacuentos para niños pequeños que ya se mueven, con música, movimiento, rimas y cuentos.",
 "Walking toddlers (1 and up) + caregiver":"Niños que ya caminan (desde 1 año) + un adulto",
 "A 30-minute music-and-movement class to rock out with your toddler. Registration recommended; limited walk-in spots.":"Una clase de 30 minutos de música y movimiento para bailar con tu niño pequeño. Se recomienda inscribirse; pocos lugares sin inscripción.",
 "Ages 1–3 + caregiver":"1–3 años + un adulto",
 "A storytime for babies and toddlers of all abilities, with music, movement, rhymes and stories.":"Un cuentacuentos para bebés y niños pequeños de todas las capacidades, con música, movimiento, rimas y cuentos.",
 "Birth–age 2 + caregiver":"0–2 años + un adulto",
 "Books and songs, then a simple craft or toy play for babies and toddlers.":"Libros y canciones, y luego una manualidad sencilla o juego con juguetes para bebés y niños pequeños.",
 "Stories, songs, rhymes and movement for budding bookworms.":"Cuentos, canciones, rimas y movimiento para pequeños lectores.",
 "Ages 1–4 + caregiver":"1–4 años + un adulto",
 "Gentle yoga poses for bonding time with your baby. Registration required.":"Posturas suaves de yoga para compartir con tu bebé. Inscripción obligatoria.",
 "Babies + caregiver":"Bebés + un adulto",
 "Gentle yoga and movement for you and your toddler. Bring a yoga mat; space is limited.":"Yoga suave y movimiento para ti y tu niño pequeño. Trae un tapete de yoga; el cupo es limitado.",
 "Ages 2–4 + caregiver":"2–4 años + un adulto",
 "A fall program run by the library's teen and children's departments. Check with the library for details and sign-up.":"Un programa de otoño de los departamentos de adolescentes e infantil de la biblioteca. Pregunta en la biblioteca por los detalles y la inscripción.",
 "Kids":"Niños",
 "A new monthly art project with Kristin Cafferty: a castle (Oct 7, ages 5–8), a neon skull (Oct 14, ages 8–12), 3-D hot cocoa (Nov 12, ages 5–8) and a city perspective (Nov 18, ages 8–12). Registration required.":"Un proyecto de arte nuevo cada mes con Kristin Cafferty: un castillo (7 de oct., 5–8 años), una calavera neón (14 de oct., 8–12 años), chocolate caliente en 3D (12 de nov., 5–8 años) y una ciudad en perspectiva (18 de nov., 8–12 años). Inscripción obligatoria.",
 "Ages 5–8 or 8–12 (varies)":"5–8 u 8–12 años (varía)",
 "A four-part art series with multi-day projects. Currently full; check for openings.":"Una serie de arte de cuatro partes con proyectos de varios días. Por ahora está llena; consulta si hay lugares.",
 "Grades K–5":"Kínder a 5.º grado",
 "Learn to draw Halloween monsters for spooky season. Registration required.":"Aprende a dibujar monstruos de Halloween. Inscripción obligatoria.",
 "The Grove School Theater Troupe brings the picture book to life in a short live performance. Registration recommended.":"La compañía de teatro de Grove School da vida al libro ilustrado en una breve función en vivo. Se recomienda inscribirse.",
 "Kids of all ages":"Niños de todas las edades",
 "See the unveiling of a new mural made of hundreds of LEGO pieces, created as a fundraiser for the CT Cancer Foundation.":"Asiste a la presentación de un nuevo mural hecho con cientos de piezas de LEGO, creado para recaudar fondos para la CT Cancer Foundation.",
 "All ages":"Todas las edades",
 "Build a spooky graham-cracker house. Each registration is one house, so sign up each child separately; arrive within 15 minutes of the start.":"Construye una casita espeluznante de galletas graham. Cada inscripción es una casita, así que inscribe a cada niño por separado; llega dentro de los primeros 15 minutos.",
 "Preschool–grade 5":"Preescolar a 5.º grado",
 "Swing by to put together a simple printable craft: a magnetic crow (Oct 24) or a silly dove (Nov 21).":"Pasa a armar una manualidad sencilla: un cuervo magnético (24 de oct.) o una paloma chistosa (21 de nov.).",
 "Paint a spider and weave its web in the Children's Room. Registration required.":"Pinta una araña y teje su telaraña en la sala infantil. Inscripción obligatoria.",
 "Ages 5 and up":"Desde 5 años",
 "A Halloween storytime, then a costume parade down the main hallway and a treat from the treasure chest.":"Un cuentacuentos de Halloween, luego un desfile de disfraces por el pasillo principal y un premio del cofre del tesoro.",
 "Babies and kids of all ages":"Bebés y niños de todas las edades",
 "Halloween trunk-or-treating on the Madison Green. The Scranton Library will be there in costume with candy and program info.":"Dulces desde los autos en el Madison Green para Halloween. La Scranton Library estará disfrazada, con dulces e información de sus programas.",
 "Make a decorative jar filled with the scents of autumn. Registration required.":"Haz un frasco decorativo lleno de los aromas del otoño. Inscripción obligatoria.",
 "Spend the Election Day school holiday meeting and learning about opossums. Registration required.":"Pasa el día sin clases de las elecciones conociendo y aprendiendo sobre las zarigüeyas. Inscripción obligatoria.",
 "Kids and teens":"Niños y adolescentes",
 "Explore the physics of simple machines by building working launchers.":"Explora la física de las máquinas simples construyendo lanzadores que funcionan.",
 "Ages 6–11":"6–11 años",
 "Turn ticket stubs, photos and other keepsakes into a handmade journal.":"Convierte boletos, fotos y otros recuerdos en un diario hecho a mano.",
 "Play xylophones, maracas and drums, then march, skip and gallop with ribbons and a parachute.":"Toca xilófonos, maracas y tambores, y luego marcha, salta y galopa con listones y un paracaídas.",
 "Babies to preschoolers":"Bebés a preescolares",
 "Half bubbles, half parachute play to songs by the biggest female pop stars of the 1980s through 2010s.":"Mitad burbujas, mitad juego con paracaídas al ritmo de las grandes estrellas pop femeninas de los años 80 a 2010.",
 "Ages 1–5":"1–5 años",
 "Shake it off with music, crafts and other Swiftie fun.":"Baila con música, manualidades y más diversión para fans de Taylor Swift.",
 "Stomp, dance and sing along with Michele Urban in a family music program.":"Pisotea, baila y canta con Michele Urban en un programa musical familiar.",
 "Babies through grade 3":"Bebés a 3.er grado",
 "Mr. Neil reads The Leaf Thief by Alice Hemming, then kids make a fall squirrel craft.":"Mr. Neil lee The Leaf Thief de Alice Hemming y luego los niños hacen una manualidad de ardilla otoñal.",
 "Ages 2–6":"2–6 años",
 "Video games, crafts and snacks for tweens over Thanksgiving weekend. Registration recommended.":"Videojuegos, manualidades y bocadillos para preadolescentes el fin de semana de Acción de Gracias. Se recomienda inscribirse.",
 "Grades 4 and up":"Desde 4.º grado",
 "Madison lights its tree on the Green in early December, usually a Friday evening around 6 pm, with Santa and music. This year's date isn't posted yet.":"Madison enciende su árbol en el Green a principios de diciembre, normalmente un viernes por la noche alrededor de las 6, con Santa y música. La fecha de este año aún no se ha publicado.",
 "Madison Town Green":"Madison Town Green",
 "A drop-in Itty Bitty Meetup four days a week, a rotating lineup of baby and toddler storytimes, music and yoga, monthly art with Kristin, and free weekly craft kits from the 'library faerie.'":"Itty Bitty Meetup sin inscripción cuatro días a la semana, cuentacuentos, música y yoga para bebés y niños pequeños que van rotando, arte mensual con Kristin y kits de manualidades gratis cada semana del 'hada de la biblioteca'.",
 "Free":"Gratis",
}

# ---- Playbook pass (Oct 4) ----
MP="meigs-point"
TOWN["venues"][MP]=["Meigs Point Nature Center","Hammonasset Beach State Park, 1288 Boston Post Rd"]
TOWN["venueMeta"][MP]=[None,1]
TOWN["events"]+=[
 {"t":"Astronomy Night at Meigs Point","v":MP,"when":[W("2026-11-06",[])],"ages":"Kids and families","a":["preschool","big"],"check":True,"src":"https://www.meigspointnaturecenter.org/",
  "blurb":"An evening of stargazing at the nature center. Check its website for the time and details."},
]
TOWN["classes"]+=[
 {"id":"waves-dance","c":"dance","n":"Waves Academy of Dance","u":"https://www.wavesaod.com/",
  "blurb":"Ballet, jazz, lyrical, contemporary, tap and hip hop classes starting as young as age 1, plus dance-based tumbling and competition teams.",
  "ages":"From age 1","where":"175 Fort Path Rd"},
 {"id":"limelite-madison","c":"dance","n":"Limelite Dance Studio","u":"https://www.limelitedancestudio.com/",
  "blurb":"A dance studio with classes from 18 months through adult and performance teams for ages 5–18. The 2026–27 schedule is posted.",
  "ages":"18 months–adult","where":"168 Boston Post Rd (also in Guilford)"},
]
PLACES["rain"].insert(1,("Meigs Point Nature Center","Free, at Hammonasset: a saltwater touch tank and live turtles, snakes, fish and crabs. Open Tuesday–Sunday, 10–5 through October and 10–4 November–March.","Gratis, en Hammonasset: un tanque táctil de agua salada y tortugas, serpientes, peces y cangrejos vivos. Abre de martes a domingo, de 10 a 5 hasta octubre y de 10 a 4 de noviembre a marzo."))
PLACES["rain"].append(("Einstein's Attic","An independent toy store with educational toys, games and free gift wrapping (140 Samson Rock Dr).","Una juguetería independiente con juguetes educativos, juegos y envoltura de regalo gratis (140 Samson Rock Dr)."))
PLACES["out"]=[p if p[0]!="Hammonasset Beach State Park" else ("Hammonasset Beach State Park","Connecticut's longest public beach, with a boardwalk, a 3.4-mile paved trail and picnic areas.","La playa pública más larga de Connecticut, con malecón, un sendero pavimentado de 5.5 km y áreas de picnic.") for p in PLACES["out"]]
ES.update({
 "An evening of stargazing at the nature center. Check its website for the time and details.":"Una noche para observar las estrellas en el centro de naturaleza. Consulta su sitio web para la hora y los detalles.",
 "Ballet, jazz, lyrical, contemporary, tap and hip hop classes starting as young as age 1, plus dance-based tumbling and competition teams.":"Clases de ballet, jazz, lírico, contemporáneo, tap y hip hop desde 1 año, además de acrobacia para danza y equipos de competencia.",
 "From age 1":"Desde 1 año",
 "A dance studio with classes from 18 months through adult and performance teams for ages 5–18. The 2026–27 schedule is posted.":"Una escuela de danza con clases desde los 18 meses hasta adultos y equipos de presentación para 5–18 años. El horario 2026–27 ya está publicado.",
 "18 months–adult":"18 meses–adultos",
 "168 Boston Post Rd (also in Guilford)":"168 Boston Post Rd (también en Guilford)",
})
