#!/usr/bin/env node
'use strict';
/* CT Kids Calendar — calendar-feed importer (step 2 of 2: publish a reviewed draft).

   Usage (from the repo root):
     node tools/approve-imports.js <town>               publish every candidate marked "keep": true (✅ in the review)
     node tools/approve-imports.js <town> --only 1,4,7  publish exactly these numbers from the review
     node tools/approve-imports.js <town> --skip 3,5    publish the ✅ items except these
     node tools/approve-imports.js <town> --dry         show what would happen, change nothing

   What it does:
   - Replaces this town's previously imported events from the same source(s) with the new
     selection (so re-running an import refreshes dates instead of piling up copies).
     Hand-curated events in <town>/index.html are never touched.
   - Writes shared/imports/<town>.json (the data) and shared/imports/<town>.js (what the page loads).
   - Adds <script src="/shared/imports/<town>.js"> to the town page, just before app.js, if missing.
   Afterwards run: node shared/build-stats.js */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const args = process.argv.slice(2);
const slug = args.find(a => !a.startsWith('--') && !/^[\d,\s]+$/.test(a));
const listOpt = name => { const i = args.indexOf('--' + name); return i >= 0 ? new Set(String(args[i + 1] || '').split(',').map(n => +n.trim()).filter(Boolean)) : null; };
const only = listOpt('only'), skip = listOpt('skip'), dry = args.includes('--dry');
if (!slug) { console.error('Usage: node tools/approve-imports.js <town> [--only 1,2] [--skip 3] [--dry]'); process.exit(1); }

const draftFile = path.join(__dirname, 'drafts', `${slug}.draft.json`);
if (!fs.existsSync(draftFile)) { console.error(`No draft for ${slug}. Run: node tools/import-events.js ${slug}`); process.exit(1); }
const draft = JSON.parse(fs.readFileSync(draftFile, 'utf8'));
const config = JSON.parse(fs.readFileSync(path.join(__dirname, 'sources.json'), 'utf8'));

const chosen = draft.candidates.filter(c => only ? only.has(c.n) : c.keep && !(skip && skip.has(c.n)));
const readSources = draft.sources.filter(s => !s.error).map(s => s.name);

const importsDir = path.join(ROOT, 'shared', 'imports');
const jsonFile = path.join(importsDir, `${slug}.json`);
const data = fs.existsSync(jsonFile) ? JSON.parse(fs.readFileSync(jsonFile, 'utf8')) : { venues: {}, venueMeta: {}, events: [] };

const before = data.events.length;
data.events = data.events.filter(e => !readSources.includes(e.imp));   // refresh, don't pile up
const replaced = before - data.events.length;
data.events.push(...chosen.map(c => c.event));

// make sure every venue used exists (hand-curated venues win if the key is already defined)
for (const s of config.towns[slug] || []) {
  if (s.venueName) { data.venues[s.venue] = [s.venueName, s.address || '']; data.venueMeta[s.venue] = [null, s.indoor === false ? 0 : 1]; }
}
data.updated = new Date().toISOString().slice(0, 10);

console.log(`${slug}: publishing ${chosen.length} imported event(s)${replaced ? `, replacing ${replaced} from the last import of the same source(s)` : ''}. Total imported for this town: ${data.events.length}.`);
for (const c of chosen) console.log(`  ${c.n}. ${c.event.t}`);
if (dry) { console.log('(dry run — nothing written)'); process.exit(0); }

fs.mkdirSync(importsDir, { recursive: true });
fs.writeFileSync(jsonFile, JSON.stringify(data, null, 1) + '\n');
fs.writeFileSync(path.join(importsDir, `${slug}.js`),
  `/* Auto-generated by tools/approve-imports.js from shared/imports/${slug}.json on ${data.updated}. Don't edit by hand; re-run the importer instead. */\n` +
  `(function () {\n  var I = ${JSON.stringify({ venues: data.venues, venueMeta: data.venueMeta, events: data.events })};\n` +
  `  var T = window.TOWN; if (!T) return;\n` +
  `  T.venues = Object.assign({}, I.venues, T.venues);\n  T.venueMeta = Object.assign({}, I.venueMeta, T.venueMeta || {});\n` +
  `  T.events = T.events.concat(I.events);\n})();\n`);

const page = path.join(ROOT, slug, 'index.html');
let html = fs.readFileSync(page, 'utf8');
const tag = `<script src="/shared/imports/${slug}.js"></script>`;
if (!html.includes(tag)) {
  if (!html.includes('<script src="/shared/app.js"></script>')) { console.error(`Couldn't find the app.js script tag in ${slug}/index.html — add ${tag} before it by hand.`); process.exit(1); }
  html = html.replace('<script src="/shared/app.js"></script>', `${tag}\n<script src="/shared/app.js"></script>`);
  fs.writeFileSync(page, html);
  console.log(`Added the imports script tag to ${slug}/index.html.`);
}
console.log('Done. Now run: node shared/build-stats.js');
